import Link from "next/link";
import { ArrowIcon } from "@/components/arrow-icon";
import { demoAreas, demoNews, demoProducts } from "@/lib/content";
import { MediaImage } from "@/components/media-image";

const scienceImage = "https://images.unsplash.com/photo-1581093588401-fbb62a02f120?auto=format&fit=crop&w=1500&q=90";
const facilityImage = "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=85";

export default function HomePage() {
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><span className="demo-note"><span className="demo-dot" /> Pharmaceutical company · demo concept</span><h1>Advancing healthcare through science.</h1><p>A considered demonstration of how a pharmaceutical company can present research, quality, and a structured product portfolio—with every example clearly marked for review.</p><div className="hero-actions"><Link className="button" href="/products">Explore our products <ArrowIcon direction="up-right" /></Link><Link className="button button-secondary" href="/about">Discover the company</Link></div><div className="hero-proof"><span className="proof-rule" /> All brand and portfolio content on this site is illustrative</div></div><div className="hero-visual"><MediaImage src={scienceImage} alt="Researcher working in a contemporary laboratory" sizes="(max-width: 760px) 100vw, 50vw" className="hero-photo" /><div className="image-overlay" /><span className="hero-index">Science · Demo image</span><div className="hero-caption"><strong>A clearer view of complex science</strong><span>Illustrative corporate concept—not a verified company profile</span></div></div></div></section>
    <nav className="service-nav" aria-label="Explore Pharmora demo sections"><div className="container service-links"><Link href="/products">Product information <ArrowIcon direction="right" /></Link><Link href="/therapeutic-areas">Therapeutic areas <ArrowIcon direction="right" /></Link><Link href="/quality">Quality approach <ArrowIcon direction="right" /></Link><Link href="/research">Research & development <ArrowIcon direction="right" /></Link></div></nav>
    <section className="section section-white"><div className="container editorial-grid editorial-intro"><div className="editorial-photo"><MediaImage src="https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=85" alt="Laboratory team reviewing scientific work" /></div><div className="editorial-copy"><span className="demo-note"><span className="demo-dot" /> About this demonstration</span><h2>Built around clarity, care, and scientific discipline.</h2><p>This concept explores how a pharmaceutical organization might communicate its work with clarity. Company history, leadership, capabilities, and all supporting facts must be supplied and verified by the organization.</p><Link className="text-link" href="/about">Learn about this concept <ArrowIcon direction="right" /></Link></div></div></section>
    <section className="section section-aqua section-areas"><div className="container"><div className="section-heading"><h2>Therapeutic areas, thoughtfully organized.</h2><p>Illustrative category structure only. No products, treatments, or health outcomes are represented as approved or available.</p></div><div className="area-grid">{demoAreas.map((area) => <Link className="area-item" href={`/therapeutic-areas/${area.slug}`} key={area.slug}><strong>{area.title}</strong><span>{area.detail}</span></Link>)}</div><Link className="text-link" href="/therapeutic-areas">View all therapeutic areas <ArrowIcon direction="right" /></Link></div></section>
    <section className="section section-products"><div className="container"><div className="section-heading"><h2>A sample of the product catalogue.</h2><p>Example entries demonstrate structured product presentation. Names, compounds, strengths, and presentations are not verified medicines.</p></div><div className="product-gallery">{demoProducts.map((product) => <article className="product-card" key={product.slug}><div className="product-art"><MediaImage src={product.image} alt="Illustrative product image" sizes="(max-width: 760px) 100vw, 33vw" /><span className="product-stamp">Demo example</span></div><div className="product-info"><span className="product-type">{product.area} · Demo listing</span><h3>{product.name}</h3><p>{product.generic}</p><div className="product-meta"><span>{product.form}</span><span>·</span><span>{product.strength}</span></div><Link className="text-link" href={`/products/${product.slug}`}>View example details <ArrowIcon direction="right" /></Link></div></article>)}</div></div></section>
    <section className="section-tight section-quality"><div className="container quality-band"><div className="quality-image"><MediaImage src={facilityImage} alt="Laboratory equipment in a quality-control environment" /></div><div className="quality-copy"><span className="demo-note"><span className="demo-dot" /> Quality · concept section</span><h2>Confidence begins with transparent standards.</h2><p>This section is a placeholder for verified quality systems, manufacturing information, and approved certificates. No certification or manufacturing claim is made here.</p><div className="quality-points"><span>Quality assurance</span><span>Quality control</span><span>Verified documentation</span></div><Link className="text-link" href="/quality" style={{ color: "#80dcda" }}>Explore quality approach <ArrowIcon direction="right" /></Link></div></div></section>
    <section className="section section-facts"><div className="container facts-layout"><div className="facts-intro"><span className="demo-note"><span className="demo-dot" /> Facts, not assumptions</span><h2>Company facts belong to the company.</h2><p>No operating history, product totals, markets, or workforce figures were provided. These fields remain intentionally unfilled.</p></div><div className="stat-row"><div className="stat-item"><strong>Not supplied</strong><span>Company history</span></div><div className="stat-item"><strong>Not supplied</strong><span>Portfolio size</span></div><div className="stat-item"><strong>Not supplied</strong><span>Markets served</span></div><div className="stat-item"><strong>Not supplied</strong><span>Team size</span></div></div></div></section>
    <section className="section section-aqua"><div className="container research-layout research-feature"><div className="research-visual"><MediaImage src="https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=85" alt="Scientist examining laboratory samples" /></div><div className="research-copy"><span className="demo-note"><span className="demo-dot" /> Research & development</span><h2>Research is a practice—not a slogan.</h2><p className="prose">A space for the real methods, partnerships, and research priorities of the organization. No pipeline, clinical program, or research capability is claimed in this demonstration.</p><Link className="text-link" href="/research">Explore the research section <ArrowIcon direction="right" /></Link></div></div></section>
    <section className="section section-white section-news"><div className="container"><div className="section-heading"><h2>Notes from the newsroom.</h2><p>Sample editorial cards are clearly labeled and carry no company announcements or factual claims.</p><Link className="text-link" href="/news">Visit newsroom <ArrowIcon direction="right" /></Link></div><div className="news-grid">{demoNews.map((story) => <article className="news-card" key={story.slug}><div className="news-image"><MediaImage src={story.image} alt="Illustrative laboratory scene" sizes="(max-width: 760px) 100vw, 33vw" /></div><div className="news-copy"><time>{story.date}</time><h3>{story.title}</h3><Link href={`/news/${story.slug}`}>Read demo story <ArrowIcon direction="right" /></Link></div></article>)}</div></div></section>
    <section className="section-tight section-careers"><div className="container cta-band"><div className="cta-copy"><span className="demo-note"><span className="demo-dot" /> Careers · sample content</span><h2>Make room for meaningful work.</h2><p>Roles shown are examples, not current vacancies.</p></div><Link className="button" href="/careers">View demo opportunities <ArrowIcon direction="right" /></Link></div></section>
  </>;
}
